### ISSUE TITLE
Missing basic matchers

### ISSUE THREAD

**Issue by krzkaczor** [earl-js/earl#48]
## TODO:

- [x] containerWith - partially matches iterables (arrays/sets)
- [x] arrayWith - partially matches only arrays
- [x] objectwith - partially matches objects

Example:

```typescript
const container = new Set()
set.add('beer')
expect(container).toEqual(expect.containerWith('beer'))


expect(['apple', 'beer']).toEqual(expect.arrayWith('apple'))

expect({a: 1, b:2, c: 3}).toEqual(expect.objectWith({c: 3}))
```
Later we can expand `arrayWith` and `containerWith` to match multiple values like:

```typescript
expect(['apple', 'beer']).toEqual(expect.arrayWith('apple', 'beer'))
```

Jest has `toContain` and it works with arrays and iterables: https://jestjs.io/docs/en/using-matchers#arrays-and-iterables

Chai has aliases like: `.includes`, `.contain`, and `.include`, which we probably shouldn't try to mimic 😆

**Comment by grzpab** [comment]
@krzkaczor I will implement `arrayWith` and open a PR once the move to the monorepo has been finished.
Should other iterables like Sets and Maps be considered for matchers?

**Comment by krzkaczor** [comment]
> Should other iterables like Sets and Maps be considered for matchers?

I think, not necessary now... Personally, I don't use these Sets too often, people can use `containerWith` for now.

**Comment by grzpab** [comment]
@krzkaczor as I have already implemented `arrayWith`, I will implement `objectWith`

**Comment by krzkaczor** [comment]
Closed by 
https://github.com/earl-js/earl/pull/71
https://github.com/earl-js/earl/pull/72
https://github.com/earl-js/earl/pull/74
